# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/pixarninja/Git/shortest_path_algorithm

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/pixarninja/Git/shortest_path_algorithm

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pixarninja/Git/shortest_path_algorithm/CMakeFiles /home/pixarninja/Git/shortest_path_algorithm/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pixarninja/Git/shortest_path_algorithm/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named tessellate

# Build rule for target.
tessellate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tessellate
.PHONY : tessellate

# fast build rule for target.
tessellate/fast:
	$(MAKE) -f CMakeFiles/tessellate.dir/build.make CMakeFiles/tessellate.dir/build
.PHONY : tessellate/fast

#=============================================================================
# Target rules for targets named pop

# Build rule for target.
pop: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pop
.PHONY : pop

# fast build rule for target.
pop/fast:
	$(MAKE) -f CMakeFiles/pop.dir/build.make CMakeFiles/pop.dir/build
.PHONY : pop/fast

#=============================================================================
# Target rules for targets named brute_force

# Build rule for target.
brute_force: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 brute_force
.PHONY : brute_force

# fast build rule for target.
brute_force/fast:
	$(MAKE) -f CMakeFiles/brute_force.dir/build.make CMakeFiles/brute_force.dir/build
.PHONY : brute_force/fast

#=============================================================================
# Target rules for targets named shortest_path

# Build rule for target.
shortest_path: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 shortest_path
.PHONY : shortest_path

# fast build rule for target.
shortest_path/fast:
	$(MAKE) -f CMakeFiles/shortest_path.dir/build.make CMakeFiles/shortest_path.dir/build
.PHONY : shortest_path/fast

#=============================================================================
# Target rules for targets named compare

# Build rule for target.
compare: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 compare
.PHONY : compare

# fast build rule for target.
compare/fast:
	$(MAKE) -f CMakeFiles/compare.dir/build.make CMakeFiles/compare.dir/build
.PHONY : compare/fast

#=============================================================================
# Target rules for targets named multiple

# Build rule for target.
multiple: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 multiple
.PHONY : multiple

# fast build rule for target.
multiple/fast:
	$(MAKE) -f CMakeFiles/multiple.dir/build.make CMakeFiles/multiple.dir/build
.PHONY : multiple/fast

#=============================================================================
# Target rules for targets named plot

# Build rule for target.
plot: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 plot
.PHONY : plot

# fast build rule for target.
plot/fast:
	$(MAKE) -f CMakeFiles/plot.dir/build.make CMakeFiles/plot.dir/build
.PHONY : plot/fast

source/brute_force.o: source/brute_force.c.o

.PHONY : source/brute_force.o

# target to build an object file
source/brute_force.c.o:
	$(MAKE) -f CMakeFiles/brute_force.dir/build.make CMakeFiles/brute_force.dir/source/brute_force.c.o
.PHONY : source/brute_force.c.o

source/brute_force.i: source/brute_force.c.i

.PHONY : source/brute_force.i

# target to preprocess a source file
source/brute_force.c.i:
	$(MAKE) -f CMakeFiles/brute_force.dir/build.make CMakeFiles/brute_force.dir/source/brute_force.c.i
.PHONY : source/brute_force.c.i

source/brute_force.s: source/brute_force.c.s

.PHONY : source/brute_force.s

# target to generate assembly for a file
source/brute_force.c.s:
	$(MAKE) -f CMakeFiles/brute_force.dir/build.make CMakeFiles/brute_force.dir/source/brute_force.c.s
.PHONY : source/brute_force.c.s

source/compare.o: source/compare.c.o

.PHONY : source/compare.o

# target to build an object file
source/compare.c.o:
	$(MAKE) -f CMakeFiles/compare.dir/build.make CMakeFiles/compare.dir/source/compare.c.o
.PHONY : source/compare.c.o

source/compare.i: source/compare.c.i

.PHONY : source/compare.i

# target to preprocess a source file
source/compare.c.i:
	$(MAKE) -f CMakeFiles/compare.dir/build.make CMakeFiles/compare.dir/source/compare.c.i
.PHONY : source/compare.c.i

source/compare.s: source/compare.c.s

.PHONY : source/compare.s

# target to generate assembly for a file
source/compare.c.s:
	$(MAKE) -f CMakeFiles/compare.dir/build.make CMakeFiles/compare.dir/source/compare.c.s
.PHONY : source/compare.c.s

source/multiple_contours.o: source/multiple_contours.cpp.o

.PHONY : source/multiple_contours.o

# target to build an object file
source/multiple_contours.cpp.o:
	$(MAKE) -f CMakeFiles/multiple.dir/build.make CMakeFiles/multiple.dir/source/multiple_contours.cpp.o
.PHONY : source/multiple_contours.cpp.o

source/multiple_contours.i: source/multiple_contours.cpp.i

.PHONY : source/multiple_contours.i

# target to preprocess a source file
source/multiple_contours.cpp.i:
	$(MAKE) -f CMakeFiles/multiple.dir/build.make CMakeFiles/multiple.dir/source/multiple_contours.cpp.i
.PHONY : source/multiple_contours.cpp.i

source/multiple_contours.s: source/multiple_contours.cpp.s

.PHONY : source/multiple_contours.s

# target to generate assembly for a file
source/multiple_contours.cpp.s:
	$(MAKE) -f CMakeFiles/multiple.dir/build.make CMakeFiles/multiple.dir/source/multiple_contours.cpp.s
.PHONY : source/multiple_contours.cpp.s

source/plot.o: source/plot.c.o

.PHONY : source/plot.o

# target to build an object file
source/plot.c.o:
	$(MAKE) -f CMakeFiles/plot.dir/build.make CMakeFiles/plot.dir/source/plot.c.o
.PHONY : source/plot.c.o

source/plot.i: source/plot.c.i

.PHONY : source/plot.i

# target to preprocess a source file
source/plot.c.i:
	$(MAKE) -f CMakeFiles/plot.dir/build.make CMakeFiles/plot.dir/source/plot.c.i
.PHONY : source/plot.c.i

source/plot.s: source/plot.c.s

.PHONY : source/plot.s

# target to generate assembly for a file
source/plot.c.s:
	$(MAKE) -f CMakeFiles/plot.dir/build.make CMakeFiles/plot.dir/source/plot.c.s
.PHONY : source/plot.c.s

source/pop_reverse.o: source/pop_reverse.cpp.o

.PHONY : source/pop_reverse.o

# target to build an object file
source/pop_reverse.cpp.o:
	$(MAKE) -f CMakeFiles/pop.dir/build.make CMakeFiles/pop.dir/source/pop_reverse.cpp.o
.PHONY : source/pop_reverse.cpp.o

source/pop_reverse.i: source/pop_reverse.cpp.i

.PHONY : source/pop_reverse.i

# target to preprocess a source file
source/pop_reverse.cpp.i:
	$(MAKE) -f CMakeFiles/pop.dir/build.make CMakeFiles/pop.dir/source/pop_reverse.cpp.i
.PHONY : source/pop_reverse.cpp.i

source/pop_reverse.s: source/pop_reverse.cpp.s

.PHONY : source/pop_reverse.s

# target to generate assembly for a file
source/pop_reverse.cpp.s:
	$(MAKE) -f CMakeFiles/pop.dir/build.make CMakeFiles/pop.dir/source/pop_reverse.cpp.s
.PHONY : source/pop_reverse.cpp.s

source/shortest_path.o: source/shortest_path.cpp.o

.PHONY : source/shortest_path.o

# target to build an object file
source/shortest_path.cpp.o:
	$(MAKE) -f CMakeFiles/shortest_path.dir/build.make CMakeFiles/shortest_path.dir/source/shortest_path.cpp.o
.PHONY : source/shortest_path.cpp.o

source/shortest_path.i: source/shortest_path.cpp.i

.PHONY : source/shortest_path.i

# target to preprocess a source file
source/shortest_path.cpp.i:
	$(MAKE) -f CMakeFiles/shortest_path.dir/build.make CMakeFiles/shortest_path.dir/source/shortest_path.cpp.i
.PHONY : source/shortest_path.cpp.i

source/shortest_path.s: source/shortest_path.cpp.s

.PHONY : source/shortest_path.s

# target to generate assembly for a file
source/shortest_path.cpp.s:
	$(MAKE) -f CMakeFiles/shortest_path.dir/build.make CMakeFiles/shortest_path.dir/source/shortest_path.cpp.s
.PHONY : source/shortest_path.cpp.s

source/tessellate.o: source/tessellate.cpp.o

.PHONY : source/tessellate.o

# target to build an object file
source/tessellate.cpp.o:
	$(MAKE) -f CMakeFiles/tessellate.dir/build.make CMakeFiles/tessellate.dir/source/tessellate.cpp.o
.PHONY : source/tessellate.cpp.o

source/tessellate.i: source/tessellate.cpp.i

.PHONY : source/tessellate.i

# target to preprocess a source file
source/tessellate.cpp.i:
	$(MAKE) -f CMakeFiles/tessellate.dir/build.make CMakeFiles/tessellate.dir/source/tessellate.cpp.i
.PHONY : source/tessellate.cpp.i

source/tessellate.s: source/tessellate.cpp.s

.PHONY : source/tessellate.s

# target to generate assembly for a file
source/tessellate.cpp.s:
	$(MAKE) -f CMakeFiles/tessellate.dir/build.make CMakeFiles/tessellate.dir/source/tessellate.cpp.s
.PHONY : source/tessellate.cpp.s

source/vector.o: source/vector.cpp.o

.PHONY : source/vector.o

# target to build an object file
source/vector.cpp.o:
	$(MAKE) -f CMakeFiles/shortest_path.dir/build.make CMakeFiles/shortest_path.dir/source/vector.cpp.o
.PHONY : source/vector.cpp.o

source/vector.i: source/vector.cpp.i

.PHONY : source/vector.i

# target to preprocess a source file
source/vector.cpp.i:
	$(MAKE) -f CMakeFiles/shortest_path.dir/build.make CMakeFiles/shortest_path.dir/source/vector.cpp.i
.PHONY : source/vector.cpp.i

source/vector.s: source/vector.cpp.s

.PHONY : source/vector.s

# target to generate assembly for a file
source/vector.cpp.s:
	$(MAKE) -f CMakeFiles/shortest_path.dir/build.make CMakeFiles/shortest_path.dir/source/vector.cpp.s
.PHONY : source/vector.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... tessellate"
	@echo "... pop"
	@echo "... brute_force"
	@echo "... shortest_path"
	@echo "... compare"
	@echo "... multiple"
	@echo "... plot"
	@echo "... source/brute_force.o"
	@echo "... source/brute_force.i"
	@echo "... source/brute_force.s"
	@echo "... source/compare.o"
	@echo "... source/compare.i"
	@echo "... source/compare.s"
	@echo "... source/multiple_contours.o"
	@echo "... source/multiple_contours.i"
	@echo "... source/multiple_contours.s"
	@echo "... source/plot.o"
	@echo "... source/plot.i"
	@echo "... source/plot.s"
	@echo "... source/pop_reverse.o"
	@echo "... source/pop_reverse.i"
	@echo "... source/pop_reverse.s"
	@echo "... source/shortest_path.o"
	@echo "... source/shortest_path.i"
	@echo "... source/shortest_path.s"
	@echo "... source/tessellate.o"
	@echo "... source/tessellate.i"
	@echo "... source/tessellate.s"
	@echo "... source/vector.o"
	@echo "... source/vector.i"
	@echo "... source/vector.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

